# Generated by Django 5.2.2 on 2025-06-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircrafttype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.category')),
            ],
        ),
    ]
